<?php

declare(strict_types=1);

describe('Character Sequence Recovery Tests', function (): void {
    it('handles various character sequences', function (string $template): void {
        $doc = $this->parse($template);
        expect($doc->render())->toBe($template);
    })->with([
        '{{{{',
        '}}}}',
        '{{}}',
        '}{',
        '{{}}{{}}'.'{{}}',
        '{{ "{" }}',
        '{{ "}" }}',
        '{{ "{{}}" }}',
        '{!! "{" !!}',
        '@@',
        '@@@',
        '@@@@',
        '@@ @if',
        '@@@if',
        'email@example.com',
        '@@if($x)',
        '@{{ $x }}',
        '@@{{ $x }}',
        '@123',
        '<<',
        '>>',
        '<>',
        '><',
        '<<<',
        '>>>',
        '< >',
        '> <',
        '<div<<span>',
        '<div>><span>',
        '<{a',
        '<x-<![CDATA[\'span',
        '</endphp@<\'endif',
        '<{phpspan/@endforeach>foreach".@if(]',
        '<phpfalse<![CDATA[/datafalse,@endif])',
        '<n<<_>',
        '<{\'\'}=}<?',
        "</\r{{",
        '<e!@php/}',
        "<\r{",
        '<?',
        '?>',
        '<??>',
        '?><?',
        '<??php',
        '<?php ?>?>',
        '{{ $x ?? $y }}',
        '{{ $a ?: $b }}',
        '{!',
        '!}',
        '{!!}',
        '{!!!}',
        '{!!!!}',
        '<!',
        '<!-',
        '<!-->',
        '<![',
        '<![CDATA[',
        '{{-',
        '{{--',
        '{{---',
        '--}}',
        '---}}',
        '{{----}}',
        '<!-',
        '<!--',
        '--->',
        '<!---->',
    ]);
});
