<?php

declare(strict_types=1);

describe('Interrupted Construct Recovery ', function (): void {
    it('handles recovers from various construct interruptions', function (string $template): void {
        $doc = $this->parse($template);
        expect($doc->render())->toBe($template);
    })->with([
        '{{ $x @if($y) }}',
        '{{ $x @if($y) $z }}',
        '{{ @include("partial") }}',
        '{{ $items @foreach($items as $item) }}',
        '{!! $x @if($y) !!}',
        '{!! @yield("section") !!}',
        '{{ $x <?php echo 1; ?> }}',
        '{{ <?php ?> $y }}',
        '{!! $x <?= $y ?> !!}',
        '{{ $a <?php if($b): ?> $c }}',
        '{{ $x <div> }}',
        '{{ <span>text</span> }}',
        '{{ $a <br/> $b }}',
        '{!! $x <script> !!}',
        '{{ </div> $y }}',
        '{{ $x {{-- comment --}} }}',
        '{{ {{-- --}} $y }}',
        '{{ $a <!-- html --> $b }}',
        '{!! {{-- blade --}} !!}',
        '{{ $x {{ $y }} }}',
        '{{ {{ $nested }} }}',
        '{!! {{ $x }} !!}',
        '{{ {!! $raw !!} }}',
        '{{{ {{ $x }} }}}',
        '@if({{ $condition }})',
        '@foreach({{ $items }} as $item)',
        '@include({{ $partial }})',
        '@section({{ $name }})',
        '@php({{ $code }})',
        '@if(<?php echo $x; ?>)',
        '@foreach(<?= $items ?> as $item)',
        '@include(<?php getView(); ?>)',
        '@php(<?php nested(); ?>)',
        '@if(<div>)',
        '@foreach(<span> as $item)',
        '@include(<template>)',
        '@section(<slot>)',
        '@if({{-- comment --}})',
        '@foreach({{-- items --}} as $item)',
        '@include(<!-- partial -->)',
        '@if(@isset($x))',
        '@foreach(@each() as $item)',
        '@include(@yield("name"))',
        '@section(@parent)',
        '<?php {{ $x }} ?>',
        '<?php @if($x) ?>',
        '<?php {!! $y !!} ?>',
        '<?php {{-- comment --}} ?>',
        '<?= {{ $x }} ?>',
        '<?php <div> ?>',
        '<?php echo "<span>"; ?>',
        '<?php <br/> ?>',
        '<?= <input/> ?>',
        '<div {{ $attrs }}>',
        '<span @if($x)class="a"@endif>',
        '<input {!! $attrs !!}/>',
        '<a {{-- comment --}} href="#">',
        '<div @class(["foo"])>',
        '<div <?php echo $attr; ?>>',
        '<span <?= $class ?>>',
        '<input <?php attrs(); ?>/>',
        '<div class="{{ $class }}">',
        '<div class="@if($x)active@endif">',
        '<div class="<?= $class ?>">',
        '<div data-json=\'{{ json_encode($data) }}\'>',
        '<div onclick="{{ $handler }}">',
        '<a href="{{ route("home") }}">',
    ]);
});
